name: insta_assets_picker
description: An image picker similar with Instagram, supports multi picking, crop and aspect ratio.
version: 0.0.1
repository: https://github.com/LeGoffMael/insta_assets_picker

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_crop:
    git:
      url: https://github.com/LeGoffMael/image_crop
      ref: mergedBranch
  wechat_assets_picker: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

screenshots:
  - description: 'Scroll animation'
    path: assets/scroll.webp
  - description: 'Crop & export'
    path: assets/crop-export.webp